[build]
builder = "NIXPACKS"
buildCommand = "cd apps/web && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd apps/web && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "20"